### ISSUE TITLE
Unpublished content is shown when using model_set

### ISSUE THREAD

**Issue by ngraef** [CoJMC/jaam#18]
examples: project.story_set, gallery.photogalleryitem_set

**Comment by colemickens** [comment]
When did you poll last? I committed what should have been the fix for this.

**Comment by ngraef** [comment]
30 minutes ago.

**Comment by colemickens** [comment]
Ugh, I think I know why, but this effectively makes this feature useless. I know of a work around, I'll look into it.

**Comment by colemickens** [comment]
This should be fixed, as well as the API issues:
1. The default model manager is now the published-filtered model manager. Every where in the system, unpublished data is filtered out.
2. I added an exception to (1) such that if the request.path.startswith("/admin"), everything is shown so that the admin... you know... doesn't become useless.
3. The API (sadly via copy/pasting the `queryset=[blah]` to inside `get_object_list(s,r): return [blah]`) should now follow the guidelines for published and unpublished content. The issue was that the ModelResource inside TastyPie stores a QuerySet, not a reference the the callable in the ModelManager (which is when/where the filtering occurs).
4. As a "good?" side effect... Haystack is (limited to) only indexing published content.

**Comment by ngraef** [comment]
Holy Twizzlers, Batman! That's a lot of console output!
`request: pubd
hello?
manager: pubd
hello?
...`
Hello. Good day, sir. But it works! Well done.

Something I noticed: in the admin listings, items are now sorted oldest to newest. Previously, the most recently added items were shown first. Changing this is simple, but we should decide which is better for the user (probably the latter).
